### ISSUE TITLE
Add part-of relations to lateral forebrain bundle

### ISSUE THREAD

**Issue by cmungall** [cerivs/zebrafish-anatomical-ontology#126]
Related to https://github.com/obophenotype/uberon/issues/1280

```
[Term]
id: ZFA:0007012
name: lateral forebrain bundle
namespace: zebrafish_anatomy
synonym: "lateral forebrain bundles" EXACT PLURAL []
xref: TAO:0007012
is_a: ZFA:0001682  ! white matter
relationship: end ZFS:0000044 ! Adult
relationship: start ZFS:0000033 ! Hatching:Long-pec
```

Can you add a definition?

Also, hard to tell without def, but judging from name, should be related to forebrain?

**Comment by cerivs** [comment]
Done will be in next release.
Definition
In the adult bilaterally paired compact tract located lateral to the medial forebrain bundle that extends to the diencephalon.  Formed from several fascicles that  originate in the precommissural telencephalon and converge rostrocaudally.  In the seven day old fish bilaterally paired bundle that runs caudally from the anterior commissure to the forebrain. In the caudal  diencephalon the bundle divides  into  two  parts.   The thinner part runs more laterally and ventrally, and the thicker part was located more medially and dorsally. Both bundles run in the caudal direction  toward  the  cranial  wall  of  the  lateral  recess  of  the diencephalic   ventricle,   where   they   apparently exchange some fibers. Then, they continue in the caudal  direction,  surrounding  the lateral  recess from  the  ventral  and dorsal side, and meet close to the caudal wall of lateral  recess at the level  of  the  commissure  of  the  posterior  tuberculum.
