### ISSUE TITLE
NTR: terms related to neurocranium

### ISSUE THREAD

**Issue by sabrinatoro** [cerivs/zebrafish-anatomical-ontology#131]
From ZDB-PUB-160411-1:
I am either missing some anatomy terms, or I am unable to identify the corresponding terms to curate this publication. These terms are: 
- **postchordal neurocranium**
- **anterior/posterior basicapsular commissure** [these elements encircle the developing ear, so I think that these terms would be children of "auditory capsule", which already has children terms] 
- **lateral commissure**

I cannot find any definition for these terms, only images with annotations. 

The ontology would look like this: 
neurocranium 
> prechordal (anterior region of the neurocranium, neural crest-derived)
> postchordal (posterior region of the neurocranium)
>> parachordals
>> lateral commissure
>> occipital arches
>> auditory capsule
>>>anterior basicapsular commissure (abc)
>>>posterior basicapsular commissure (pbc)

**Comment by cerivs** [comment]
Are these bone or nervous system structures?

**Comment by sabrinatoro** [comment]
these are bones

**Comment by sabrinatoro** [comment]
From ZDB-PUB-160411-1:
The neurocranium can be split into anterior and posterior
halves (dashed line in Fig. 1A). While much research has been
directed at the development of the neural crest-derived prechordal
neurocranium (Fig. 1A, prech.), little is known of the development
of the postchordal neurocranium (Fig. 1A, postch.). The
postchordal neurocranium includes the parachordal cartilages
(pc), which abut the notochord (n); as well as the anterior and
posterior basicapsular commissures (abc and pbc, respectively)
which encircle the developing ear, the lateral commissures (lc),
and the occipital arches (oc) (Fig. 1A; de Beer, 1937).

**Comment by cerivs** [comment]
Made new terms anterior basicapsular commissure, lateral basicapsular commissure and posterior basicapsular commissure.   Use post composition or individual cartilages for basil region of neurocranium.  Figuring out neurocranial subdivisions is a moderately large project

**Comment by sabrinatoro** [comment]
@cerivs : 
what terms should I use for : 
- postchordal neurocranium
- lateral commissure
? 

Not sure which correct (as in "most precise") terms should be used.
Thanks!

**Comment by cerivs** [comment]
lateral commissure = lateral basicapsular commissure

postchordal neurocranium= posterior region neurocranium
