### ISSUE TITLE
notochord should not be part_of occipital region

### ISSUE THREAD

**Issue by cmungall** [cerivs/zebrafish-anatomical-ontology#133]
ZFA:0000135 ! notochord is part-of ZFA:0001414 ! occipital region in ZFA, I don't think this is right, e.g

http://dev.biologists.org/content/132/11/2503
![image](https://cloud.githubusercontent.com/assets/50745/23592060/0b4b0eb0-01b0-11e7-8743-04888730e98d.png)

**Comment by cerivs** [comment]
Fixed in last release
