### ISSUE TITLE
NTR: Midbrain Hindbrain Boundary constriction

### ISSUE THREAD

**Issue by sabrinatoro** [cerivs/zebrafish-anatomical-ontology#135]
New term: Midbrain Hindbrain Boundary Constriction
synonyms: MHBC
definition: portion of the midbrain hindbrain boundary that is constricted

should be a child of : Midbrain Hindbrain Boundary (ZFA:0000042)

This term is needed for curation of ZDB-PUB-170204-10

**Comment by ybradford** [comment]
publication for development of this structure: PMCID: PMC2780020 Mech Dev. 2008 Nov–Dec; 125(11-12): 974–983. ZDB-PUB-080825-24

**Comment by sabrinatoro** [comment]
This term is needed for curation of ZDB-PUB-181012-11

**Comment by ybradford** [comment]
I've added this term to the ZFA. should be available with next release.
