### ISSUE TITLE
NTR: caudal hematopoietic tissue

### ISSUE THREAD

**Issue by sabrinatoro** [cerivs/zebrafish-anatomical-ontology#138]
blood island (ZFA:0000094) is restricted to 22h until 30h developmental stages. 

Many authors refer to CHT (or blood island) until as late as 4dpf. 
[see ZDB-PUB-170815-11].
We might need to consider expanding the stages for this term. 

Thanks

**Comment by sabrinatoro** [comment]
After talking with Ceri, we realized that "blood island" and the "caudal hematopoietic tissue" are actually 2 different structures. (the title of this case what updated)

A review of the structures and hematopoiesis in zebrafish can be found here: https://zfin.org/ZDB-PUB-100820-15

**Comment by cerivs** [comment]
Will be in the next release.
