### ISSUE TITLE
change primary name for YSL

### ISSUE THREAD

**Issue by cmungall** [cerivs/zebrafish-anatomical-ontology#140]
http://www.ontobee.org/search?ontology=ZFA&keywords=YSL&submit=Search+terms

To synchronize with:
https://github.com/obophenotype/uberon/issues/1461

**Comment by doughowe** [comment]
and probably I-YSL and E-YSL

**Comment by ybradford** [comment]
@cmungall to be clear you are asking for it to change to yolk syncytial layer not yolk sac layer -right?

**Comment by cmungall** [comment]
correct. Sorry for the forked conversation, see some of the comments on the linked uberon tracker

**Comment by cerivs** [comment]
I updated this in the ZFA.  Will be out with the next release.
