### ISSUE TITLE
NTR: endolymphatic sac

### ISSUE THREAD

**Issue by sabrinatoro** [cerivs/zebrafish-anatomical-ontology#141]
NTR: endolymphatic sac
information about this structure can be found in PMID:29916365 (ZDB-PUB-180322-24).

Proposed definition: dead-end epithelial tube connected to the inner ear. The apical junctions and basal lamellae in the ES appear to function pressure relief valve for the inner ear.

ontology: endolymphatic sac is_part_of inner ear (ZFA:0000217) 

stages: (based on PMID:29916365/ZDB-PUB-180322-24): 36h to unknown

**Comment by cerivs** [comment]
In adults, the endolymphatic duct and sac are partially encased within the temporal bone such that the distal end of the endolymphatic sac protrudes out of the temporal bone into the cranial cavity .

**Comment by cerivs** [comment]
Will be in the next release
