### ISSUE TITLE
Run of ROBOT report: duplicate definitions.

### ISSUE THREAD

**Issue by matentzn** [cerivs/zebrafish-anatomical-ontology#143]
ZFA has some duplicate definitions, probably a copy-paste error. See below!

Undifferentiated mesodermal component of early trunk or tail segment or metamere
derived from paraxial mesoderm; forms the myotome
sclerotome and perhaps dermatome.
- [x] ZFA:0000072
- [x] ZFA:0000073
- [x] ZFA:0000074
- [x] ZFA:0000156
- [x] ZFA:0000157
- [x] ZFA:0000725
- [x] ZFA:0000726
- [x] ZFA:0000727
- [x] ZFA:0000728
- [x] ZFA:0000730
- [x] ZFA:0000731
- [x] ZFA:0000732
- [x] ZFA:0000733
- [x] ZFA:0000851
- [x] ZFA:0000852
- [x] ZFA:0000853
- [x] ZFA:0000854
- [x] ZFA:0000855
- [x] ZFA:0000856
- [x] ZFA:0000857
- [x] ZFA:0000858
- [x] ZFA:0000974
- [x] ZFA:0000975
- [x] ZFA:0000976
- [x] ZFA:0000977
- [x] ZFA:0000978
- [x] ZFA:0000980
- [x] ZFA:0000981
- [x] ZFA:0000982
- [x] ZFA:0000983

Somite-derived body wall muscle present ventral to the horizontal myoseptum.
- [x] ZFA:0000767
- [x] ZFA:0000768
- [x] ZFA:0000769
- [x] ZFA:0000770
- [x] ZFA:0000771
- [x] ZFA:0000772
- [x] ZFA:0000774
- [x] ZFA:0000775
- [x] ZFA:0000776
- [x] ZFA:0000777
- [x] ZFA:0000891
- [x] ZFA:0000892
- [x] ZFA:0000894
- [x] ZFA:0000895
- [x] ZFA:0000896
- [x] ZFA:0000897
- [x] ZFA:0000898
- [x] ZFA:0000899
- [x] ZFA:0000900
- [x] ZFA:0000901
- [x] ZFA:0000925
- [x] ZFA:0000937
- [x] ZFA:0000946
- [x] ZFA:0000957
- [x] ZFA:0000968
- [x] ZFA:0000979
- [x] ZFA:0000986
- [x] ZFA:0000987
- [x] ZFA:0000988
- [x] ZFA:0000989

Somite-derived body wall muscle present dorsal to the horizontal myoseptum.
- [x] ZFA:0000718
- [x] ZFA:0000729
- [x] ZFA:0000739
- [x] ZFA:0000740
- [x] ZFA:0000741
- [x] ZFA:0000742
- [x] ZFA:0000743
- [x] ZFA:0000744
- [x] ZFA:0000745
- [x] ZFA:0000746
- [x] ZFA:0000747
- [x] ZFA:0000748
- [x] ZFA:0000749
- [x] ZFA:0000751
- [x] ZFA:0000864
- [x] ZFA:0000865
- [x] ZFA:0000866
- [x] ZFA:0000867
- [x] ZFA:0000868
- [x] ZFA:0000869
- [x] ZFA:0000870
- [x] ZFA:0000872
- [x] ZFA:0000873
- [x] ZFA:0000874
- [x] ZFA:0000991
- [x] ZFA:0001001
- [x] ZFA:0001012
- [x] ZFA:0001023
- [x] ZFA:0001030
- [x] ZFA:0001040

Protoglomeruli in the medial  region of the glomerular layer of the olfactory bulb. 
- [x] ZFA:0005671
- [x] ZFA:0005726
- [x] ZFA:0005727
- [x] ZFA:0005728
- [x] ZFA:0005729

Protoglomeruli in the lateral  region of the glomerular layer of the olfactory bulb.
- [x] ZFA:0005669- [ ] ZFA:0005717
- [x] ZFA:0005718
- [x] ZFA:0005719
- [x] ZFA:0005720

Protoglomeruli in the central zone  of the glomerular layer of the olfactory bulb.  The central zone protoglomeruli have somewhat indistinct boundaries.
- [x] ZFA:0005670
- [x] ZFA:0005721
- [x] ZFA:0005722
- [x] ZFA:0005723
- [x] ZFA:0005724
- [x] ZFA:0005725

Portion of the somite giving rise to body wall muscle masses.
- [x] ZFA:0000044
- [x] ZFA:0000801
- [x] ZFA:0000802
- [x] ZFA:0000803
- [x] ZFA:0000804
- [x] ZFA:0000805
- [x] ZFA:0000807
- [x] ZFA:0000808
- [x] ZFA:0000809
- [x] ZFA:0000810
- [x] ZFA:0000924
- [x] ZFA:0000926
- [x] ZFA:0000927
- [x] ZFA:0000928
- [x] ZFA:0000929
- [x] ZFA:0000930
- [x] ZFA:0000931
- [x] ZFA:0000932
- [x] ZFA:0000933
- [x] ZFA:0000934
- [x] ZFA:0001013
- [x] ZFA:0001014
- [x] ZFA:0001015
- [x] ZFA:0001016
- [x] ZFA:0001017
- [x] ZFA:0001018
- [x] ZFA:0001019
- [x] ZFA:0001020
- [x] ZFA:0001021
- [x] ZFA:0001022

Patches of thickened
pseudostratified epithelium of the inner ear
consisting of regular arrays of sensory hair cells interspersed with supporting cells. Each patch has its own characteristic shape and polarity pattern. (See Anatomical Atlas entry for <a href='http://zfin.org/zf_info/anatomy/dict/sens/sens.html'>sensory patches of the ear</a> by T. Whitfield.)
- [x] ZFA:0000166
- [x] ZFA:0000566
- [x] ZFA:0000619

One of two large glomeruli located in the ventroposterior zone olfactory bulb.
- [x] ZFA:0005700
- [x] ZFA:0005701

One of eight distinct lateral lines in the 4-day larva. A sensory system on the surface of the fish
consisting of small sensory patches (neuromasts) distributed in discrete lines over the body surface. The lateral line system is stimulated by local water displacements and vibrations
and detects propulsion of the fish through the water
as well as facilitating shoaling
prey capture
and predator and obstacle avoidance. (See Anatomical Atlas entry for <a href='http://zfin.org/zf_info/anatomy/dict/lat_line/lat_line.html'>lateral line</a> by T. Whitfield.)
- [x] ZFA:0000259
- [x] ZFA:0000344
- [x] ZFA:0000400
- [x] ZFA:0000424
- [x] ZFA:0000443
- [x] ZFA:0000464
- [x] ZFA:0000524
- [x] ZFA:0000944
- [x] ZFA:0005112

Midbrain interneuron located in the medial midbrain.
- [x] ZFA:0005212
- [x] ZFA:0005216

Medial ventral region of the somite that will form vertebral cartilages.
- [x] ZFA:0000829
- [x] ZFA:0000830
- [x] ZFA:0000831
- [x] ZFA:0000832
- [x] ZFA:0000833
- [x] ZFA:0000834
- [x] ZFA:0000835
- [x] ZFA:0000836
- [x] ZFA:0000837
- [x] ZFA:0000839
- [x] ZFA:0000952
- [x] ZFA:0000953
- [x] ZFA:0000954
- [x] ZFA:0000955
- [x] ZFA:0000956
- [x] ZFA:0000958
- [x] ZFA:0000959
- [x] ZFA:0000960
- [x] ZFA:0000961
- [x] ZFA:0000962
- [x] ZFA:0001036
- [x] ZFA:0001037
- [x] ZFA:0001038
- [x] ZFA:0001039
- [x] ZFA:0001041
- [x] ZFA:0001042
- [x] ZFA:0001043
- [x] ZFA:0001044
- [x] ZFA:0001045
- [x] ZFA:0001046

Lip that covers the lower portion of the mouth.
- [x] ZFA:0005225
- [x] ZFA:0005226

Hypobranchial ossifications 1-3 develop in the small hypobranchial cartilages that lie between the medial tips of the ceratobranchials and copula 1. The first and second hypobranchials are small and irregular in shape; one or both ossifications are absent in some adults.
- [x] ZFA:0001233
- [x] ZFA:0001235
- [x] ZFA:0001236

Hindbrain segment or neuromere.
- [x] ZFA:0000069
- [x] ZFA:0000153
- [x] ZFA:0000822
- [x] ZFA:0000823
- [x] ZFA:0000948
- [x] ZFA:0000949
- [x] ZFA:0001031
- [x] ZFA:0001032

Glomerulus located in the mediodorsal zone of the olfactory bulb.
- [x] ZFA:0005709
- [x] ZFA:0005710
- [x] ZFA:0005711
- [x] ZFA:0005712
- [x] ZFA:0005713
- [x] ZFA:0005714

Glomerulus located in the lateral zone of the olfactory bulb.
- [x] ZFA:0005703
- [x] ZFA:0005704
- [ ] ZFA:0005705

Fluid-filled brain cavity.
- [x] ZFA:0000110
- [ ] ZFA:0000161

Diencephalic nucleus which is part of the caudal tuberculum. From Neuroanatomy of the Zebrafish Brain.
- [x] ZFA:0000294
- [x] ZFA:0000325
- [x] ZFA:0000397

Cranial nerve that innervates gill muscles.
- [x] ZFA:0000453
- [x] ZFA:0000668

A RoL2 interneuron that is part of rhombomere 2.
- [x] ZFA:0005199
- [x] ZFA:0005200

**Comment by cerivs** [comment]
Most of these are necessary but not sufficient usually missing positional or shape information.  They were made intentionally since it was the best that could be done at the time with the resources allocated.  I will start updating.

**Comment by matentzn** [comment]
Ahhh ok! Thanks for the clarification!

**Comment by ybradford** [comment]
@cerivs I fixed a large swath. only 10 more need fixed

**Comment by cerivs** [comment]
These should no longer be a problem.
