### ISSUE TITLE
NTR: melanoleucophore // xantholeucophore

### ISSUE THREAD

**Issue by sabrinatoro** [cerivs/zebrafish-anatomical-ontology#148]
**term name:** melanoleucophore
**definition:** leucophore which contains a reflective but opaque white material and lack pteridines and carotenoids. These cells sometimes contained melanin, similar to melanophores.
**Parent term:** ZFA:0009261 (leucophore)
**reference:** PMID:31138706 (ZDB-PUB-190530-2)

**term name:** xantholeucophore
**definition:** Leucophore containing orange and white pigment. These cells contained pteridines and carotenoids, similar to xanthophores, 
**Parent term:** ZFA:0009261 (leucophore)
**reference:** PMID:31138706 (ZDB-PUB-190530-2)

**Comment by cerivs** [comment]
Will be in the next release with more complete definitions.
