### ISSUE TITLE
NTR: Germline Stem Cell

### ISSUE THREAD

**Issue by sabrinatoro** [cerivs/zebrafish-anatomical-ontology#150]
**Proposed name:** germline stem cell
**Proposed synonym:** GSC

**Proposed definition:** A stem cell that can give rise to cell types of the germ-line. A stem cell is a relatively undifferentiated cell that retains the ability to divide and proliferate throughout life to provide progenitor cells that can differentiate into specialized cells.

[the other stem cell terms in ZFA are defined as "a stem cell which ...". There is no definition for what a stem cell is. The definition for the stem cell in the proposed definition is the one from CL_0000034)

**Proposed parent:** (is_a) cell (ZFA:0009000) 
**Proposed cross reference:** CL_0000014

This term is required to curate ZDB-PUB-190214-9

**Comment by cerivs** [comment]
Will be in next release.
